### ISSUE TITLE
'SIOCGIFMTU failed' after some network changes

### ISSUE THREAD

**Issue by DavidAsirtec** [keeshux/tunnelkit#59] opened 2019-01-30 10:10 UTC
# Summary

After succesfully creating a VPN Tunnel with your library, it crashes after some network changes (WiFi to 4G and back). 

### Steps to reproduce

Connect to WiFi and create a Tunnel, then disable Wifi and let 4G take over the connection. Wait until the Tunnel reconnects succesfully and enable WiFi. Then, wait again for the reconnection and repeat the process until the connection is down.

### What is the current bug behavior?

The connection crashes in one of the reconnections (it might be the 50th try or the 10th, looks random) for some reason and the Tunnel is not active anymore.

### What is the expected correct behavior?

The Tunnel stays active like it does with every other reconnection before the bug

### Relevant logs and/or screenshots

We get this error in the device log when the bug happens:

`SIOCGIFMTU failed: Device not configured  
NEVirtualInterfaceAdjustReadBufferSize: interface_get_mtu failed (6), defaulting to max mtu`

Our .ovpn file looks like this (Some info is erased, to maintain our client's privacy)

```
client
remote xxx.xxxxxxx.xxx xxx udp
nobind
dev tun
persist-tun
persist-key
verify-x509-name xxx.xxxxxxx.xxx name
remote-cert-tls server
cipher AES-128-CBC

<ca>
-----BEGIN CERTIFICATE-----
....
(certificate content)
....
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
....
(certificate content)
....
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
....
(certificate content)
....
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
....
(certificate content)
....
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN PRIVATE KEY-----
....
(certificate content)
....
-----END PRIVATE KEY-----
</key>
```

### Possible fixes suggested remediation

I kind of went around this issue by enabling on demand mode on my NETunnelProviderManager, with manager.onDemandRules = [OnDemandRuleConnect()], wich works for our app desired functionality and reestablishes the tunnel after it crashes.

Another bug arised when I fixed it this way, but I will describe it in another issue.

Thanks in advance

**Comment by keeshux** [comment] 2019-01-30 21:47
Those two lines in the console are issues with iOS Network Extension, they're not coming from the app. The framework is pretty buggy overall. However, it'd be interesting having a look at a bigger excerpt of the console, and see if the app may be causing it somehow.

**Comment by DavidAsirtec** [comment] 2019-01-31 08:14
Thanks for your time @keeshux !
I'm going to try and trigger the bug again, and get back to you with that excerpt.

**Comment by keeshux** [comment] 2019-02-05 20:56
This is pretty much a non-issue, disconnections may be caused by literally everything, including iOS bugs. Especially while roaming networks, disconnections may increase. I'm closing this.

**Closed by keeshux** 2019-02-05 20:56 UTC
